previewsEnabled: false
previewsExpireAfterDays: 1
databases:
  - name: repeater_world-db
    databaseName: repeater_world
    user: repeater_world
    postgresMajorVersion: 15
    plan: starter
    previewPlan: starter

envVarGroups:
  - name: repeater_world
    envVars:
      - key: ALLOW_SAMPLE_DATA_GENERATION
        value: false
        previewValue: true
      - key: DELIVER_EMAILS
        value: true
        previewValue: false
      - key: GOOGLE_GEOCODING_API_KEY
        sync: false
      - key: POSTMARK_API_TOKEN
        sync: false
      - key: MAILGUN_API_KEY
        sync: false
      - key: SAFE_EMAIL_DEST
        value: "staging@repeater.world"
      - key: SECRET_KEY_BASE
        sync: false
      - key: SENTRY_DSN
        sync: false

services:
  - type: web
    name: repeater_world-web
    plan: starter
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    previewPlan: standard
    initialDeployHook: bundle exec rake db:seed
    domains:
      - repeater.world
    envVars:
      - fromGroup: repeater_world
      - key: DATABASE_URL
        fromDatabase:
          name: repeater_world-db
          property: connectionString
      - key: FATHOM_ID
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SENTRY_DSN_FE
        sync: false

  - type: cron
    name: repeater_world-import_all
    runtime: ruby
    schedule: "0 6 * * ?" # every day at 6am UTC
    buildCommand: "./bin/render-build.sh"
    startCommand: rake import_all
    envVars:
      - fromGroup: repeater_world
      - key: DATABASE_URL
        fromDatabase:
          name: repeater_world-db
          property: connectionString

  - type: cron
    name: repeater_world-import_artscipub
    runtime: ruby
    schedule: "0 2 15 * *" # every Saturday at 2am UTC
    buildCommand: "./bin/render-build.sh"
    startCommand: rake import_artscipub
    envVars:
      - fromGroup: repeater_world
      - key: DATABASE_URL
        fromDatabase:
          name: repeater_world-db
          property: connectionString
