require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/repeaters", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Repeater. As you add validations to Repeater, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Repeater.create! valid_attributes
      get repeaters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      repeater = Repeater.create! valid_attributes
      get repeater_url(repeater)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_repeater_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      repeater = Repeater.create! valid_attributes
      get edit_repeater_url(repeater)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Repeater" do
        expect {
          post repeaters_url, params: {repeater: valid_attributes}
        }.to change(Repeater, :count).by(1)
      end

      it "redirects to the created repeater" do
        post repeaters_url, params: {repeater: valid_attributes}
        expect(response).to redirect_to(repeater_url(Repeater.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Repeater" do
        expect {
          post repeaters_url, params: {repeater: invalid_attributes}
        }.to change(Repeater, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post repeaters_url, params: {repeater: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested repeater" do
        repeater = Repeater.create! valid_attributes
        patch repeater_url(repeater), params: {repeater: new_attributes}
        repeater.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the repeater" do
        repeater = Repeater.create! valid_attributes
        patch repeater_url(repeater), params: {repeater: new_attributes}
        repeater.reload
        expect(response).to redirect_to(repeater_url(repeater))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        repeater = Repeater.create! valid_attributes
        patch repeater_url(repeater), params: {repeater: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested repeater" do
      repeater = Repeater.create! valid_attributes
      expect {
        delete repeater_url(repeater)
      }.to change(Repeater, :count).by(-1)
    end

    it "redirects to the repeaters list" do
      repeater = Repeater.create! valid_attributes
      delete repeater_url(repeater)
      expect(response).to redirect_to(repeaters_url)
    end
  end
end
